In [1]:
import os
import csv
import pandas as pd
import win32com.client
import numpy as np

In [ ]:
# As the default setting of the collection software stores the event data as '.xls' extensions, this cell will
# be used to convert each file into a '.csv' file for easier use.

xl = win32com.client.gencache.EnsureDispatch('Excel.Application')
filePath = "0path"

for root,dirs,files in os.walk(filePath):
    for file in files:
        if file.endswith(".xls"):
            x = os.path.join(root,file)
            xl.Workbooks.Open(os.path.join(root,file))
            xl.ActiveWorkbook.SaveAs(Filename=x.replace('.xls', '.csv'),
                                     FileFormat=win32com.client.constants.xlCSVMSDOS,
                                     CreateBackup=True)
            xl.ActiveWorkbook.Close(SaveChanges=True)

In [ ]:
# the code in this cell creates a "masterfile", and appends any rows with pass or shot events to it.

filesList = []
writer = open("xG-shots-master.csv", 'w')
writer = csv.writer(writer, delimiter='\t')
for root,dirs,files in os.walk(filePath):
    for file in files:
        if file.endswith(".csv"):
            filesList.append(file)
            f = open(os.path.join(root,file), "r")
            reader = csv.reader(f, delimiter='\t')

            for column in reader:
                # print(column[0])
                column_list = column[0].split(',')
                # print(column_list)
                if ("Pass" in column_list[1] or "Goal" in column_list[1] or "Shot" in column_list[1]) and ("Kick" not in column_list[1]):
                    writer.writerow(column)

In [2]:
df = pd.read_csv("xG-shots-master.csv")
df.head()

,1,R Grounded Pass,53:14:13,53:16:13,53:17:13,Unnamed: 5,TG,d7,TG.1,a9,...,Unnamed: 146,Unnamed: 147,Unnamed: 148,Unnamed: 149,Unnamed: 150,Unnamed: 151,Unnamed: 152,Unnamed: 153,Unnamed: 154,Unnamed: 155
0,2.0,R Grounded Pass,53:16:19,53:18:19,53:19:19,NaN,G6,a10,G3,e12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3.0,R Grounded Pass,53:19:03,53:21:03,53:22:03,NaN,G3,e12,G2,g6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4.0,R Grounded Pass,53:26:15,53:28:15,53:29:15,NaN,B5,c3,B2,d2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5.0,R Grounded Pass,53:30:02,53:32:02,53:33:02,NaN,B2,e2,TB,a5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6.0,R Grounded Pass,53:32:04,53:34:04,53:35:04,NaN,TB,a5,B5,c2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN